---
# Source: kargo/charts/kargo/templates/system-resources-namespace/role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-system-resources-reader
  namespace: kargo-system-resources
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-system-resources-reader
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-controller
- kind: ServiceAccount
  namespace: kargo
  name: kargo-external-webhooks-server
---
# Source: kargo/charts/kargo/templates/system-resources-namespace/role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-system-resources-admin
  namespace: kargo-system-resources
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-system-resources-admin
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-api
- kind: ServiceAccount
  namespace: kargo
  name: kargo-admin
