---
# Source: calico/charts/tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec:
  {}
---
# Source: calico/charts/tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Goldmane
metadata:
  name: default
spec:
  {}
---
# Source: calico/charts/tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  imagePullSecrets: []
  kubeletVolumePluginPath: None
  kubernetesProvider: ""
---
# Source: calico/charts/tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Whisker
metadata:
  name: default
spec:
  {}
