---
# Source: kargo-config-infra/templates/kargo-github-signing-key.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kargo-github-signing-key
  namespace: homelab-infra
  labels:
    kargo.akuity.io/cred-type: git
spec:
  itemPath: "vaults/homelab/items/kargo-github-signing-key"
