---
# Source: kargo/charts/kargo/templates/common/cluster-roles.yaml
# This role is bound to the API server's and the Kargo admin's ServiceAccounts
# in project namespaces as they are created. This dynamically extends their most
# sensitive permissions on a per-namespace basis instead of granting them
# cluster-wide.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-project-admin
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - secrets
    - serviceaccounts
  verbs:
    - "*"
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
    - roles
  verbs:
    - "*"
---
# Source: kargo/charts/kargo/templates/common/cluster-roles.yaml
# This role is bound to the external webhooks server's ServiceAccount in
# project namespaces as they are created. This dynamically extends its most
# sensitive permissions on a per-namespace basis instead of granting them
# cluster-wide. Additional uses for this role are anticipated in the future.
#
# NOTE: Controller ServiceAccounts are bound to a DIFFERENT role
# (kargo-controller-read-secrets) as new project namespaces are created. That
# role has the same permissions as this one. The external webhooks server is the
# second (after the controller) component requiring permission to read secrets
# in project namespaces only, so this role was created as a generic role for
# that purpose in the likely event that still more components will require these
# permissions in the future. The controller is NOT transitioning to use this
# more generically named role because its existing kargo-controller-read-secrets
# role is publicly documented in places and is therefore hard to change.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-project-secrets-reader
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
