---
# Source: kargo/charts/kargo/templates/cluster-secrets-namespace/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-cluster-secrets
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
