---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-infra
    targetRevision: env/prod/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-infra
    targetRevision: env/prod/cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-kargo-config-infra
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: homelab-infra
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-infra
    targetRevision: env/prod/kargo-config-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-kargo
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kargo
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-infra
    targetRevision: env/prod/kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-onepassword-connect
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: onepassword-connect
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-infra
    targetRevision: env/prod/onepassword-connect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
