---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-argocd
  namespace: homelab-infra
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: argocd
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-infra
      - name: targetBranch
        value: env/prod/argocd
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/argocd/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: argocd
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/argocd-values.yaml
          #- ${{ vars.path_src }}/applications/argocd/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: argocd
          namespace: argocd
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/argocd
          outPath: ${{ vars.path_out }}/deploy/argocd
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/argocd
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-cert-manager
  namespace: homelab-infra
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: cert-manager
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-infra
      - name: targetBranch
        value: env/prod/cert-manager
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/cert-manager/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: cert-manager
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/cert-manager-values.yaml
          #- ${{ vars.path_src }}/applications/cert-manager/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: cert-manager
          namespace: cert-manager
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/cert-manager
          outPath: ${{ vars.path_out }}/deploy/cert-manager
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/cert-manager
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-kargo-config-infra
  namespace: homelab-infra
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-config-infra
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-infra
      - name: targetBranch
        value: env/prod/kargo-config-infra
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/kargo-config-infra/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: kargo-config-infra
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/kargo-config-infra-values.yaml
          #- ${{ vars.path_src }}/applications/kargo-config-infra/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: kargo-config-infra
          namespace: homelab-infra
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/kargo-config-infra
          outPath: ${{ vars.path_out }}/deploy/kargo-config-infra
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/kargo-config-infra
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-kargo
  namespace: homelab-infra
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-infra
      - name: targetBranch
        value: env/prod/kargo
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/kargo/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: kargo
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/kargo-values.yaml
          #- ${{ vars.path_src }}/applications/kargo/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: kargo
          namespace: kargo
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/kargo
          outPath: ${{ vars.path_out }}/deploy/kargo
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/kargo
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-onepassword-connect
  namespace: homelab-infra
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: onepassword-connect
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-infra
      - name: targetBranch
        value: env/prod/onepassword-connect
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/onepassword-connect/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: onepassword-connect
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/onepassword-connect-values.yaml
          #- ${{ vars.path_src }}/applications/onepassword-connect/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: onepassword-connect
          namespace: onepassword-connect
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/onepassword-connect
          outPath: ${{ vars.path_out }}/deploy/onepassword-connect
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/onepassword-connect
