---
# Source: kargo/charts/kargo/templates/controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-controller
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
data:
  API_SERVER_BASE_URL: https://localhost
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "CONSOLE"
  SYSTEM_RESOURCES_NAMESPACE: "kargo-system-resources"
  IS_DEFAULT_CONTROLLER: "true"
  SHARED_RESOURCES_NAMESPACE: "kargo-shared-resources"
  ALLOW_CREDENTIALS_OVER_HTTP: "false"
  GITCLIENT_NAME: "Scott yoder"
  GITCLIENT_EMAIL: "syoder89@gmail.com"
  GITCLIENT_SIGNING_KEY_TYPE: "gpg"
  GITCLIENT_SIGNING_KEY_PATH: /etc/kargo/git/signingKey
  CACHE_BY_TAG_POLICY: "Allow"
  MAX_IMAGE_CACHE_ENTRIES: "100000"
  IMAGE_REGISTRY_RATE_LIMIT: "20"
  ARGOCD_INTEGRATION_ENABLED: "true"
  ARGOCD_NAMESPACE: argocd
  ARGOCD_WATCH_ARGOCD_NAMESPACE_ONLY: "false"
  ROLLOUTS_INTEGRATION_ENABLED: "true"
  ROLLOUTS_CONTROLLER_INSTANCE_ID: ""
  MAX_CONCURRENT_CONTROL_FLOW_RECONCILES: "4"
  MAX_CONCURRENT_PROMOTION_RECONCILES: "4"
  MAX_CONCURRENT_STAGE_RECONCILES: "4"
  MAX_CONCURRENT_WAREHOUSE_RECONCILES: "4"
  MIN_WAREHOUSE_RECONCILIATION_INTERVAL: "5m0s"
