---
# Source: kargo/charts/kargo/templates/shared-resources-namespace/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-shared-resources
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
