apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: homelab-infra
  namespace: homelab-infra
spec:
  promotionPolicies:
  - stageSelector:
      # Apply to all stages matching a glob pattern
      # YOLO
      name: "glob:prod-*"
    autoPromotionEnabled: true