{{- range $path, $_ := .Files.Glob "applications/*/Chart.yaml" }}
{{- $app := $.Files.Get $path | fromYaml }}
{{- range $env_name, $env := $.Values.envs }}
{{- if not $env.isEphemeral }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $env_name }}-{{ $app.name }}
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: {{ $.Values.kargo.projectName }}:{{ $env_name }}-{{ $app.name }}
spec:
  destination:
    name: in-cluster
    namespace: {{ $app.namespace | default $app.name }}
  project: {{ $.Values.argocd.projectName }}
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: {{ $.Values.repo.repoURL }}
    targetRevision: {{ $env.targetBranchPrefix }}/{{ $app.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ClientSideApplyMigration=false
  {{- if and (hasKey $app "argocd") (hasKey $app.argocd "ignoreDifferences") }}
  ignoreDifferences:
    {{- include "better-tpl" (list $app.argocd.ignoreDifferences (dict "Values" $.Values "app" $app "env" $env)) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}