{{- range $path, $_ := .Files.Glob "applications/*/Chart.yaml" }}
{{- $app := $.Files.Get $path | fromYaml }}
{{- range $env_name, $env := $.Values.envs }}
{{- if $env.isEphemeral }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-{{ $env_name }}-{{ $app.name }}
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: {{ $.Values.kargo.projectName }}:{{ $env_name }}-{{ $app.name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: syoder89-homelab
        # The Github repository
        repo: {{ $.Values.kargo.projectName }}
        tokenRef:
          secretName: argocd-github-pat
          key: token
      filters:
      - targetBranchMatch: "^{{ $env.targetBranchPrefix }}/{{ $app.name }}$"
      requeueAfterSeconds: 60
      values:
        appName: "pr-{{`{{ .number }}`}}-{{ $env_name }}-{{ $app.name }}"
        #appNamespace: "pr-{{`{{ .number }}`}}-{{ $app.namespace | default $app.name }}"
        # Kargo helm-template needs to know the namespace ahead of time to render properly so we cannot use PR number here
        appNamespace: "{{ $env_name }}-{{ $app.namespace | default $app.name }}"
  template:
    metadata:
      name: "{{`{{ .values.appName }}`}}"
      namespace: argocd
      annotations:
        kargo.akuity.io/authorized-stage: {{ $.Values.kargo.projectName }}:{{ $env_name }}-{{ $app.name }}
    spec:
      destination:
        name: in-cluster
        namespace: "{{`{{ .values.appNamespace }}`}}"
      project: {{ $.Values.argocd.projectName }}
      source:
        directory:
          recurse: true
        path: deploy/
        repoURL: {{ $.Values.repo.repoURL }}
        targetRevision: "{{`{{ .head_sha }}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/instance: "{{`{{ .values.appName }}`}}"
          annotations:
            argocd.argoproj.io/tracking-id: >-
              {{`{{ .values.appName }}`}}:apps/Namespace:{{`{{ .values.appNamespace }}`}}/{{`{{ .values.appNamespace }}`}}
        syncOptions:
        - CreateNamespace=true
{{- end }}
{{- end }}
{{- end }}