---
# Source: kargo/charts/kargo/templates/management-controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-management-controller
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: management-controller
data:
  EXTERNAL_WEBHOOK_SERVER_BASE_URL: https://localhost
  KARGO_NAMESPACE: kargo
  CLUSTER_SECRETS_NAMESPACE: kargo-cluster-secrets
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "CONSOLE"
  MAX_CONCURRENT_NAMESPACE_RECONCILES: "4"
  MAX_CONCURRENT_PROJECT_RECONCILES: "4"
  MAX_CONCURRENT_PROJECT_CONFIG_RECONCILES: "4"
  MAX_CONCURRENT_SERVICE_ACCOUNT_RECONCILES: "4"
