envs:
  prod:
    sources:
      direct: true
      # Not going to implement the test environment / stage yet
      # stages:
      # - test-{{ .app.name }}
    asPR: true
    isEphemeral: false
    targetBranchPrefix: env/prod
    envType: prod
  #test:
  #  sources:
  #    direct: true
  #  asPR: true
  #  isEphemeral: true
  #  targetBranchPrefix: env/test
  #  envType: test