---
# Source: kargo/charts/kargo/templates/external-webhooks-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kargo-external-webhooks-server
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: external-webhooks-server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/component: external-webhooks-server
