---
# Source: onepassword-connect/charts/connect/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onepassword-connect-operator
  labels:
    helm.sh/chart: connect-2.1.1
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: onepassword-connect-operator
  namespace: onepassword-connect
roleRef:
  kind: ClusterRole
  name: onepassword-connect-operator
  apiGroup: rbac.authorization.k8s.io
