---
# Source: onepassword-connect/charts/connect/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
  namespace: onepassword-connect
  labels:
    app.kubernetes.io/component: operator
    helm.sh/chart: connect-2.1.1
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect
  template:
    metadata:
      labels:
        name: onepassword-connect
        app.kubernetes.io/component: operator
    spec:
      tolerations:
        []
      serviceAccountName: onepassword-connect-operator
      containers:
        - name: onepassword-connect
          image: 1password/onepassword-operator:1.9.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          command: [ "/manager" ]
          args: [ --zap-log-level=info]
          env:
            - name: WATCH_NAMESPACE
              value: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onepassword-connect-operator"
            - name: POLLING_INTERVAL
              value: "600"
            - name: AUTO_RESTART
              value: "false"
            - name: OP_CONNECT_HOST
              value: "http://onepassword-connect:8080"
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onepassword-token
                  key: token
          resources:
            {}
