---
# Source: onepassword-connect/charts/connect/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassword-connect-operator
  namespace: onepassword-connect
  labels:
    helm.sh/chart: connect-2.3.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
