configPaths:
  - config/platform/global/**.yaml
  - config/platform/env-types/{{ .Values.envType }}/**.yaml
  - config/platform/envs/{{ .Values.envName }}/**.yaml
  - config/application/global/**.yaml
  - config/application/env-types/{{ .Values.envType }}/**.yaml
  - config/application/envs/{{ .Values.envName }}/**.yaml