---
# Source: kargo/charts/kargo/templates/api/cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
spec:
  dnsNames:
  - "localhost"
  issuerRef:
    kind: Issuer
    name: kargo-selfsigned-cert-issuer
  secretName: kargo-api-cert
