---
# Source: kargo/charts/kargo/templates/api/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-api
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-api
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-api
---
# Source: kargo/charts/kargo/templates/api/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-api-rollouts
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-api-rollouts
subjects:
  - kind: ServiceAccount
    namespace: kargo
    name: kargo-api
