---
# Source: kargo/charts/kargo/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: kargo
      app.kubernetes.io/instance: kargo
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        helm.sh/chart: kargo-1.8.4
        app.kubernetes.io/name: kargo
        app.kubernetes.io/instance: kargo
        app.kubernetes.io/version: "v1.8.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: api
      annotations:
        configmap/checksum: e79ee198659d04a448b8c377a9e1d30227797987273f744170c50ec4487262c6
        secret/checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      serviceAccount: kargo-api
      containers:
        - name: api
          image: ghcr.io/akuity/kargo:v1.8.4
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/kargo", "api"]
          env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: api
                divisor: "1"
                resource: limits.memory
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                containerName: api
                divisor: "1"
                resource: limits.cpu
          envFrom:
          - configMapRef:
              name: kargo-api
          - secretRef:
              name: kargo-api
          ports:
            - name: h2c
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/grpc_health_probe
                - -addr=:8080
                - -tls
                - -tls-no-verify
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/grpc_health_probe
                - -addr=:8080
                - -tls
                - -tls-no-verify
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /etc/kargo
              name: config
              readOnly: true
          resources:
            {}
      volumes:
        - name: config
          projected:
            sources:
              - secret:
                  name: kargo-api-cert
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
