---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-admin
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
    rbac.kargo.akuity.io/system-role: "true"
---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-project-creator
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
    rbac.kargo.akuity.io/system-role: "true"
---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-user
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
    rbac.kargo.akuity.io/system-role: "true"
---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-viewer
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.9.3
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.9.3"
    app.kubernetes.io/managed-by: Helm
    rbac.kargo.akuity.io/system-role: "true"
