---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-admin
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-project-creator
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-user
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
---
# Source: kargo/charts/kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-viewer
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.4"
    app.kubernetes.io/managed-by: Helm
